version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=demande
      - MYSQL_ROOT_PASSWORD=demande
    ports:
      - '3308:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  # phpmyadmin:
  #   image: phpmyadmin
  #   ports:
  #     - 8080:80
  #   environment:
  #     - PMA_ARBITRARY=1

volumes:
  db:
    driver: local
